"""resto das tabelas

Revision ID: 43a415cacd7a
Revises: 9d4680709c20
Create Date: 2025-06-25 09:27:50.753989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43a415cacd7a'
down_revision = '9d4680709c20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_categories',
    sa.Column('cat_id', sa.Integer(), nullable=False),
    sa.Column('cat_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('cat_id')
    )
    op.create_table('tb_contents',
    sa.Column('cnt_id', sa.Integer(), nullable=False),
    sa.Column('cnt_title', sa.String(length=255), nullable=False),
    sa.Column('cnt_description', sa.Text(), nullable=True),
    sa.Column('cnt_type', sa.String(length=50), nullable=False),
    sa.Column('cnt_release_date', sa.Date(), nullable=True),
    sa.Column('cnt_thumbnail', sa.String(length=255), nullable=True),
    sa.Column('cnt_url', sa.String(length=255), nullable=True),
    sa.Column('cnt_created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('cnt_id')
    )
    op.create_table('tb_users',
    sa.Column('usr_id', sa.Integer(), nullable=False),
    sa.Column('usr_name', sa.String(length=255), nullable=False),
    sa.Column('usr_email', sa.String(length=255), nullable=False),
    sa.Column('usr_password', sa.String(length=255), nullable=False),
    sa.Column('usr_profile_picture', sa.String(length=255), nullable=True),
    sa.Column('usr_bio', sa.Text(), nullable=True),
    sa.Column('usr_created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('usr_id'),
    sa.UniqueConstraint('usr_email', name='uq_usuario_email'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('tb_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tb_users_usr_email'), ['usr_email'], unique=True)

    op.create_table('tb_comments',
    sa.Column('cmt_id', sa.Integer(), nullable=False),
    sa.Column('cmt_user_id', sa.Integer(), nullable=False),
    sa.Column('cmt_content_id', sa.Integer(), nullable=False),
    sa.Column('cmt_text', sa.Text(), nullable=False),
    sa.Column('cmt_created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cmt_content_id'], ['tb_contents.cnt_id'], ),
    sa.ForeignKeyConstraint(['cmt_user_id'], ['tb_users.usr_id'], ),
    sa.PrimaryKeyConstraint('cmt_id')
    )
    op.create_table('tb_content_categories',
    sa.Column('cct_content_id', sa.Integer(), nullable=False),
    sa.Column('cct_category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cct_category_id'], ['tb_categories.cat_id'], ),
    sa.ForeignKeyConstraint(['cct_content_id'], ['tb_contents.cnt_id'], ),
    sa.PrimaryKeyConstraint('cct_content_id', 'cct_category_id')
    )
    op.create_table('tb_followers',
    sa.Column('fol_follower_id', sa.Integer(), nullable=False),
    sa.Column('fol_followed_id', sa.Integer(), nullable=False),
    sa.Column('fol_followed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fol_followed_id'], ['tb_users.usr_id'], ),
    sa.ForeignKeyConstraint(['fol_follower_id'], ['tb_users.usr_id'], ),
    sa.PrimaryKeyConstraint('fol_follower_id', 'fol_followed_id')
    )
    op.create_table('tb_likes',
    sa.Column('lik_id', sa.Integer(), nullable=False),
    sa.Column('lik_user_id', sa.Integer(), nullable=False),
    sa.Column('lik_content_id', sa.Integer(), nullable=False),
    sa.Column('lik_created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lik_content_id'], ['tb_contents.cnt_id'], ),
    sa.ForeignKeyConstraint(['lik_user_id'], ['tb_users.usr_id'], ),
    sa.PrimaryKeyConstraint('lik_id')
    )
    op.create_table('tb_private_messages',
    sa.Column('msg_id', sa.Integer(), nullable=False),
    sa.Column('msg_sender_id', sa.Integer(), nullable=False),
    sa.Column('msg_receiver_id', sa.Integer(), nullable=False),
    sa.Column('msg_text', sa.Text(), nullable=False),
    sa.Column('msg_sent_at', sa.DateTime(), nullable=False),
    sa.Column('msg_is_read', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['msg_receiver_id'], ['tb_users.usr_id'], ),
    sa.ForeignKeyConstraint(['msg_sender_id'], ['tb_users.usr_id'], ),
    sa.PrimaryKeyConstraint('msg_id')
    )
    op.create_table('tb_ratings',
    sa.Column('rat_id', sa.Integer(), nullable=False),
    sa.Column('rat_user_id', sa.Integer(), nullable=False),
    sa.Column('rat_content_id', sa.Integer(), nullable=False),
    sa.Column('rat_rating', sa.Integer(), nullable=False),
    sa.Column('rat_created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['rat_content_id'], ['tb_contents.cnt_id'], ),
    sa.ForeignKeyConstraint(['rat_user_id'], ['tb_users.usr_id'], ),
    sa.PrimaryKeyConstraint('rat_id')
    )
    op.create_table('tb_watch_history',
    sa.Column('wht_id', sa.Integer(), nullable=False),
    sa.Column('wht_user_id', sa.Integer(), nullable=False),
    sa.Column('wht_content_id', sa.Integer(), nullable=False),
    sa.Column('wht_last_watched', sa.DateTime(), nullable=False),
    sa.Column('wht_progress', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['wht_content_id'], ['tb_contents.cnt_id'], ),
    sa.ForeignKeyConstraint(['wht_user_id'], ['tb_users.usr_id'], ),
    sa.PrimaryKeyConstraint('wht_id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))

    op.drop_table('usuarios')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('senha', sa.VARCHAR(length=128), nullable=False),
    sa.Column('biografia', sa.TEXT(), nullable=True),
    sa.Column('criado_em', sa.DATETIME(), nullable=False),
    sa.Column('atualizado_em', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name=op.f('uq_usuario_email'))
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=1)

    op.drop_table('tb_watch_history')
    op.drop_table('tb_ratings')
    op.drop_table('tb_private_messages')
    op.drop_table('tb_likes')
    op.drop_table('tb_followers')
    op.drop_table('tb_content_categories')
    op.drop_table('tb_comments')
    with op.batch_alter_table('tb_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tb_users_usr_email'))

    op.drop_table('tb_users')
    op.drop_table('tb_contents')
    op.drop_table('tb_categories')
    # ### end Alembic commands ###
