"""Inicial

Revision ID: 758c0fceb5c9
Revises: 
Create Date: 2025-08-09 23:47:58.551862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '758c0fceb5c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_categories',
    sa.Column('cat_id', sa.Integer(), nullable=False),
    sa.Column('cat_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('cat_id')
    )
    op.create_table('tb_contents',
    sa.Column('cnt_id', sa.Integer(), nullable=False),
    sa.Column('cnt_title', sa.String(length=255), nullable=False),
    sa.Column('cnt_description', sa.Text(), nullable=True),
    sa.Column('cnt_type', sa.String(length=50), nullable=False),
    sa.Column('cnt_release_date', sa.Date(), nullable=True),
    sa.Column('cnt_thumbnail', sa.String(length=255), nullable=True),
    sa.Column('cnt_url', sa.String(length=255), nullable=True),
    sa.Column('cnt_created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('cnt_id')
    )
    op.create_table('tb_users',
    sa.Column('usr_id', sa.Integer(), nullable=False),
    sa.Column('usr_name', sa.String(length=255), nullable=False),
    sa.Column('usr_email', sa.String(length=255), nullable=False),
    sa.Column('usr_password', sa.String(length=255), nullable=False),
    sa.Column('usr_profile_picture', sa.String(length=255), nullable=True),
    sa.Column('usr_bio', sa.Text(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('usr_created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('usr_id'),
    sa.UniqueConstraint('usr_email', name='uq_usuario_email'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('tb_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tb_users_usr_email'), ['usr_email'], unique=True)

    op.create_table('tb_comments',
    sa.Column('cmt_id', sa.Integer(), nullable=False),
    sa.Column('cmt_user_id', sa.Integer(), nullable=False),
    sa.Column('cmt_content_id', sa.Integer(), nullable=False),
    sa.Column('cmt_text', sa.Text(), nullable=False),
    sa.Column('cmt_created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cmt_content_id'], ['tb_contents.cnt_id'], ),
    sa.ForeignKeyConstraint(['cmt_user_id'], ['tb_users.usr_id'], ),
    sa.PrimaryKeyConstraint('cmt_id')
    )
    op.create_table('tb_communities',
    sa.Column('com_id', sa.Integer(), nullable=False),
    sa.Column('com_owner_id', sa.Integer(), nullable=False),
    sa.Column('com_name', sa.String(length=255), nullable=False),
    sa.Column('com_description', sa.Text(), nullable=True),
    sa.Column('com_created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['com_owner_id'], ['tb_users.usr_id'], ),
    sa.PrimaryKeyConstraint('com_id')
    )
    op.create_table('tb_content_categories',
    sa.Column('cct_content_id', sa.Integer(), nullable=False),
    sa.Column('cct_category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cct_category_id'], ['tb_categories.cat_id'], ),
    sa.ForeignKeyConstraint(['cct_content_id'], ['tb_contents.cnt_id'], ),
    sa.PrimaryKeyConstraint('cct_content_id', 'cct_category_id')
    )
    op.create_table('tb_followers',
    sa.Column('fol_follower_id', sa.Integer(), nullable=False),
    sa.Column('fol_followed_id', sa.Integer(), nullable=False),
    sa.Column('fol_followed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fol_followed_id'], ['tb_users.usr_id'], ),
    sa.ForeignKeyConstraint(['fol_follower_id'], ['tb_users.usr_id'], ),
    sa.PrimaryKeyConstraint('fol_follower_id', 'fol_followed_id')
    )
    op.create_table('tb_likes',
    sa.Column('lik_id', sa.Integer(), nullable=False),
    sa.Column('lik_user_id', sa.Integer(), nullable=False),
    sa.Column('lik_content_id', sa.Integer(), nullable=False),
    sa.Column('lik_created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lik_content_id'], ['tb_contents.cnt_id'], ),
    sa.ForeignKeyConstraint(['lik_user_id'], ['tb_users.usr_id'], ),
    sa.PrimaryKeyConstraint('lik_id')
    )
    op.create_table('tb_private_messages',
    sa.Column('msg_id', sa.Integer(), nullable=False),
    sa.Column('msg_sender_id', sa.Integer(), nullable=False),
    sa.Column('msg_receiver_id', sa.Integer(), nullable=False),
    sa.Column('msg_text', sa.Text(), nullable=False),
    sa.Column('msg_sent_at', sa.DateTime(), nullable=False),
    sa.Column('msg_is_read', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['msg_receiver_id'], ['tb_users.usr_id'], ),
    sa.ForeignKeyConstraint(['msg_sender_id'], ['tb_users.usr_id'], ),
    sa.PrimaryKeyConstraint('msg_id')
    )
    op.create_table('tb_ratings',
    sa.Column('rat_id', sa.Integer(), nullable=False),
    sa.Column('rat_user_id', sa.Integer(), nullable=False),
    sa.Column('rat_content_id', sa.Integer(), nullable=False),
    sa.Column('rat_rating', sa.Integer(), nullable=False),
    sa.Column('rat_created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['rat_content_id'], ['tb_contents.cnt_id'], ),
    sa.ForeignKeyConstraint(['rat_user_id'], ['tb_users.usr_id'], ),
    sa.PrimaryKeyConstraint('rat_id')
    )
    op.create_table('tb_watch_history',
    sa.Column('wht_id', sa.Integer(), nullable=False),
    sa.Column('wht_user_id', sa.Integer(), nullable=False),
    sa.Column('wht_content_id', sa.Integer(), nullable=False),
    sa.Column('wht_last_watched', sa.DateTime(), nullable=False),
    sa.Column('wht_progress', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['wht_content_id'], ['tb_contents.cnt_id'], ),
    sa.ForeignKeyConstraint(['wht_user_id'], ['tb_users.usr_id'], ),
    sa.PrimaryKeyConstraint('wht_id')
    )
    op.create_table('tb_community_posts',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('post_community_id', sa.Integer(), nullable=False),
    sa.Column('post_author_id', sa.Integer(), nullable=False),
    sa.Column('post_content', sa.Text(), nullable=False),
    sa.Column('post_created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_author_id'], ['tb_users.usr_id'], ),
    sa.ForeignKeyConstraint(['post_community_id'], ['tb_communities.com_id'], ),
    sa.PrimaryKeyConstraint('post_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_community_posts')
    op.drop_table('tb_watch_history')
    op.drop_table('tb_ratings')
    op.drop_table('tb_private_messages')
    op.drop_table('tb_likes')
    op.drop_table('tb_followers')
    op.drop_table('tb_content_categories')
    op.drop_table('tb_communities')
    op.drop_table('tb_comments')
    with op.batch_alter_table('tb_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tb_users_usr_email'))

    op.drop_table('tb_users')
    op.drop_table('tb_contents')
    op.drop_table('tb_categories')
    # ### end Alembic commands ###
